image: registry.gitlab.com/dizys/node-youtube-dl-docker:latest

cache:
  paths:
    - node_modules/
    - .yarn

pages:
  only:
    - schedules
  variables:
    TZ: "Asia/Shanghai"
  before_script:
    - pwd
    - yarn install --frozen-lockfile
  script:
    - yarn watch
  artifacts:
    paths:
      - public
      - video
    expire_in: 12 days
